import React, { useState } from 'react'
import { uploadLicenseDocument } from '../api/licenseApi'
import { useLicense } from '../context/LicenseContext'

export function UploadLicensePanel() {
  const { refreshLicenseStatus } = useLicense()

  const [rawText, setRawText] = useState('')
  const [parsedPreview, setParsedPreview] = useState(null)
  const [parseError, setParseError] = useState(null)

  const [submitting, setSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState(null)
  const [submitSuccess, setSubmitSuccess] = useState(null)

  function handleTextChange(e) {
    const value = e.target.value
    setRawText(value)
    setSubmitError(null)
    setSubmitSuccess(null)

    if (!value.trim()) {
      setParsedPreview(null)
      setParseError(null)
      return
    }

    try {
      const parsed = JSON.parse(value)
      setParsedPreview(parsed)
      setParseError(null)
    } catch (err) {
      setParsedPreview(null)
      setParseError(err.message || 'Invalid JSON')
    }
  }

  function handleFileChange(e) {
    const file = e.target.files && e.target.files[0]
    if (!file) return

    setSubmitError(null)
    setSubmitSuccess(null)
    setParseError(null)
    setParsedPreview(null)

    const reader = new FileReader()
    reader.onload = (event) => {
      const text = event.target.result || ''
      setRawText(text)

      if (!text.trim()) {
        setParseError('File is empty.')
        return
      }

      try {
        const parsed = JSON.parse(text)
        setParsedPreview(parsed)
        setParseError(null)
      } catch (err) {
        setParseError(err.message || 'Invalid JSON in file')
      }
    }

    reader.onerror = () => {
      setParseError('Failed to read file.')
    }

    reader.readAsText(file, 'utf-8')
  }

  async function handleSubmit(e) {
    e.preventDefault()

    setSubmitError(null)
    setSubmitSuccess(null)

    if (!rawText.trim()) {
      setSubmitError('Please paste license JSON or load a license file first.')
      return
    }

    if (parseError) {
      setSubmitError('License JSON is invalid. Please fix the JSON first.')
      return
    }

    if (!parsedPreview) {
      setSubmitError('No parsed license available. Please check the JSON.')
      return
    }

    setSubmitting(true)
    try {
      // parsedPreview is the full { meta, payload, signature } object
      const response = await uploadLicenseDocument(parsedPreview)

      // Backend may return updated grants/status; we can show a simple success message
      setSubmitSuccess('License uploaded and validated successfully.')
      setSubmitError(null)

      // Refresh global license status (left panel)
      await refreshLicenseStatus()

      // Optionally, we could also show `response` somewhere if needed
      console.debug('Upload response:', response)
    } catch (err) {
      console.error('Failed to upload license', err)
      let message = 'Upload failed.'
      if (err.data && typeof err.data === 'object') {
        // If backend returns structured error
        if (err.data.detail) {
          message = err.data.detail
        } else if (err.data.error) {
          message = err.data.error
        }
      }
      setSubmitError(message)
      setSubmitSuccess(null)
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="panel">
      <h2>Upload / Replace License</h2>
      <p className="panel-description">
        Paste the full signed license JSON (including <code>meta</code>,{' '}
        <code>payload</code>, and <code>signature</code>), or load it from a
        file generated by the license server.
      </p>

      <form onSubmit={handleSubmit}>
        <div style={{ marginBottom: '0.75rem' }}>
          <label
            htmlFor="license-file-input"
            style={{
              display: 'inline-block',
              padding: '0.3rem 0.75rem',
              borderRadius: '999px',
              border: '1px solid #d1d5db',
              backgroundColor: '#f9fafb',
              fontSize: '0.8rem',
              cursor: 'pointer',
            }}
          >
            Choose license file…
          </label>
          <input
            id="license-file-input"
            type="file"
            accept=".json,.license,application/json"
            onChange={handleFileChange}
            style={{ display: 'none' }}
          />
          <span style={{ marginLeft: '0.5rem', fontSize: '0.8rem', color: '#6b7280' }}>
            Supported: <code>.json</code>, <code>.license</code> (JSON inside)
          </span>
        </div>

        <div style={{ marginBottom: '0.75rem' }}>
          <label
            htmlFor="license-json-input"
            style={{
              display: 'block',
              fontSize: '0.85rem',
              fontWeight: 500,
              marginBottom: '0.25rem',
            }}
          >
            License JSON
          </label>
          <textarea
            id="license-json-input"
            rows={12}
            value={rawText}
            onChange={handleTextChange}
            placeholder='{
  "meta": { "version": 1, "alg": "Ed25519", "key_id": "main-v1" },
  "payload": { "...": "..." },
  "signature": "base64url..."
}'
            style={{
              width: '100%',
              fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
              fontSize: '0.8rem',
              borderRadius: '0.5rem',
              border: '1px solid #d1d5db',
              padding: '0.5rem 0.6rem',
              boxSizing: 'border-box',
              backgroundColor: '#f9fafb',
            }}
          />
          {parseError && (
            <p style={{ marginTop: '0.3rem', color: '#b91c1c', fontSize: '0.8rem' }}>
              JSON parse error: {parseError}
            </p>
          )}
          {!parseError && parsedPreview && (
            <p style={{ marginTop: '0.3rem', color: '#16a34a', fontSize: '0.8rem' }}>
              JSON looks valid.
            </p>
          )}
        </div>

        <div style={{ marginBottom: '0.75rem' }}>
          <button
            type="submit"
            disabled={submitting || !!parseError || !rawText.trim()}
            style={{
              padding: '0.45rem 1rem',
              fontSize: '0.85rem',
              borderRadius: '999px',
              border: 'none',
              cursor: submitting ? 'default' : 'pointer',
              backgroundColor: submitting || parseError || !rawText.trim()
                ? '#e5e7eb'
                : '#2563eb',
              color: submitting || parseError || !rawText.trim()
                ? '#6b7280'
                : '#ffffff',
              fontWeight: 500,
            }}
          >
            {submitting ? 'Uploading…' : 'Upload & Activate License'}
          </button>
        </div>

        {submitError && (
          <p style={{ marginTop: '0.25rem', color: '#b91c1c', fontSize: '0.85rem' }}>
            {submitError}
          </p>
        )}
        {submitSuccess && (
          <p style={{ marginTop: '0.25rem', color: '#166534', fontSize: '0.85rem' }}>
            {submitSuccess}
          </p>
        )}
      </form>

      {parsedPreview && (
        <details
          style={{
            marginTop: '0.75rem',
            fontSize: '0.8rem',
          }}
        >
          <summary>Preview parsed license JSON</summary>
          <pre
            style={{
              background: '#f3f4f6',
              borderRadius: '0.5rem',
              padding: '0.75rem',
              marginTop: '0.4rem',
              fontSize: '0.75rem',
              overflowX: 'auto',
            }}
          >
{JSON.stringify(parsedPreview, null, 2)}
          </pre>
        </details>
      )}
    </div>
  )
}
