# Generated by Django 5.2.8 on 2025-11-19 05:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_license_json', models.JSONField()),
                ('payload', models.JSONField()),
                ('signature', models.TextField()),
                ('algorithm', models.CharField(default='Ed25519', max_length=50)),
                ('key_id', models.CharField(default='main-v1', max_length=100)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('not_yet_valid', 'Not Yet Valid'), ('invalid_signature', 'Invalid Signature'), ('tampered', 'Tampered / Payload Mismatch'), ('missing', 'No License Installed'), ('error', 'Error')], default='missing', max_length=50)),
                ('status_message', models.TextField(blank=True)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_count', models.IntegerField(default=0)),
                ('monthly_count', models.IntegerField(default=0)),
                ('last_reset_daily', models.DateField(blank=True, null=True)),
                ('last_reset_monthly', models.DateField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='licensing.installedlicense')),
            ],
        ),
    ]
