# Generated by Django 5.2.8 on 2025-11-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedlicense',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name from payload.', max_length=255),
        ),
        migrations.AddField(
            model_name='installedlicense',
            name='edition_code',
            field=models.CharField(blank=True, help_text="Edition code from payload (e.g. 'enterprise').", max_length=64),
        ),
        migrations.AddField(
            model_name='installedlicense',
            name='edition_name',
            field=models.CharField(blank=True, help_text="Edition name from payload (e.g. 'Enterprise').", max_length=128),
        ),
        migrations.AddField(
            model_name='installedlicense',
            name='license_id',
            field=models.CharField(blank=True, help_text='External license identifier as defined in the signed payload.', max_length=64),
        ),
        migrations.AddField(
            model_name='installedlicense',
            name='license_type',
            field=models.CharField(blank=True, help_text='License type (e.g. trial, subscription, perpetual).', max_length=32),
        ),
    ]
